# Phân tích và hiển thị dữ liệu

In [1]:
v = list(range(1, 6))
print(v)
print(2 * v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
import numpy as np
v = np.arange(1, 6)
print(v)
print(2 * v)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [3]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [5]:
x = [60, 70, 80, 90]
print('len(x)=',len(x))
print('x[0]x[0])
print(x[1])
print(x[-1])

len(x)= 4
60
70
90


In [4]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print('c =')
display(c)


c =


array([ 4, 10, 18])

In [8]:
import numpy as np

a = np.zeros((2,2))
display(a)

b = np.ones((3,2))
display (b)

c = np.full((4,5),7)
display(c)

d = np.eye (2)
display (d)
e = np.random.random((2,4))
display(e)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

array([[1., 0.],
       [0., 1.]])

array([[0.62481527, 0.64179666, 0.52576759, 0.03284464],
       [0.26522953, 0.22755259, 0.00870181, 0.0778684 ]])

In [13]:
import numpy as np
a = np.arange(15)
display(a)

a = a.reshape(3,5)
display(a)
display(a.shape)
display(a.ndim)
display(a.dtype.name)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

(3, 5)

2

'int64'

In [16]:
import numpy as np
a = np.array([1,2,3,4,5])
display(a)


array([1, 2, 3, 4, 5])

In [18]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]])
display (a)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [21]:
import numpy as np
a = np.array([[0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23]])
print(a)
print (a.ndim)
print (a.shape)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)


In [22]:
a = np.arange(1, 10).reshape(3,3)
display(a)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
display(a[:2,1:])
display(a[:2,1:].shape)

array([[2, 3],
       [5, 6]])

(2, 2)

# Pandas

In [8]:
import pandas as pd
a = pd.DataFrame({"a": [4, 5, 6],
"b": [7, 8, 9],
"c": [10, 11, 12]})
display(a)
display(a.loc[2])
b = pd.DataFrame([
    {'a':4,'b':7,'c':10},
    {'a':5,'b':8,'c':11},
    {'a':6,'b':9,'c':12},
 ])
display(b)
display(b.loc[1])

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

a     6
b     9
c    12
Name: 2, dtype: int64

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

a     5
b     8
c    11
Name: 1, dtype: int64

In [9]:
display(type(a))

pandas.core.frame.DataFrame

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

s = pd.Series([1,3,5,np.nan,6,8])
display(s)

dates = pd.date_range('20181001',
periods=6)
display(dates)


0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [16]:
df = pd.DataFrame(np.random.randn(6,4),
index=dates, columns=list('ABCD'))
display(df)

display(df.loc['2018-10-03'])
display(df['B'])

A         B         C         D
2018-10-01  0.427333 -2.250092  1.854427  1.417891
2018-10-02 -0.027329  0.888451 -0.625152 -0.670785
2018-10-03 -1.536821 -0.636488  1.008493  0.009742
2018-10-04 -0.785882  0.943762 -1.256434 -0.737153
2018-10-05  1.093738  0.116323  0.772944 -0.983865
2018-10-06 -1.068589  1.108167  0.539934 -0.301367

A   -1.536821
B   -0.636488
C    1.008493
D    0.009742
Name: 2018-10-03 00:00:00, dtype: float64

2018-10-01   -2.250092
2018-10-02    0.888451
2018-10-03   -0.636488
2018-10-04    0.943762
2018-10-05    0.116323
2018-10-06    1.108167
Freq: D, Name: B, dtype: float64

In [17]:
df = pd.DataFrame(np.random.randn(3,5),
index=['student1','student2','student3']
, columns=list('ABCDE'))
print(df)

                 A         B         C         D         E
student1  0.491676 -0.156636 -0.826616 -0.223709  0.030653
student2  0.972669  1.789979  1.261292  0.938823 -0.748712
student3  0.289010  1.339296 -0.888716 -0.014486  3.141013


In [18]:
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20181001'),
'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })
display(df2)

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [ ]:
import pandas as pd

# Create a DataFrame to store transactions
columns = ['Date', 'Description', 'Amount']
ledger = pd.DataFrame(columns=columns)
# Function to add a transaction
def add_transaction(date, description, amount):
    global ledger
    new_transaction = pd.DataFrame([[date, description, amount]], columns=columns)
    ledger = pd.concat([ledger, new_transaction], ignore_index=True)
# Function to view the ledger
def view_ledger():
    print(ledger)
# Function to get the current balance
def get_balance():
return ledger['Amount'].sum()
# Adding sample transactions
add_transaction('2023-11-01', 'Income', 1000)
add_transaction('2023-11-02', 'Groceries', -200)
add_transaction('2023-11-03', 'Utilities', -100)
# Viewing the ledger
view_ledger()
# Checking the current balance
print("Current Balance:", get_balance())
